@startuml

participant consumer #LightBlue
participant GraphQLService #LightGreen

consumer -> GraphQLService : graphQL query


database database #lightyellow




GraphQLService -> database: get customers with joined address and accounts

GraphQLService -> OpenAI : get greetings for all customers using DataLoaders

GraphQLService --> consumer : return all data \n(and only the data requested)\nin a single roundtrip

@enduml
